[package]
name = "ep-plant"
version = "0.1.0"
edition = "2021"

[dependencies]
ep-units = { workspace = true }
ep-core = { workspace = true }
ep-psychrometrics = { workspace = true }
ep-nodes = { workspace = true }
ep-curves = { workspace = true }
ep-fluids = { workspace = true }
serde = { workspace = true }
