[package]
name = "ep-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
ep-core = { workspace = true }
ep-weather = { workspace = true }
ep-schedule = { workspace = true }
ep-io = { workspace = true }
ep-zone-air = { workspace = true }
ep-output = { workspace = true }
ep-envelope = { workspace = true }
ep-materials = { workspace = true }
ep-surfaces = { workspace = true }
ep-solar = { workspace = true }
ep-internal-gains = { workspace = true }
ep-psychrometrics = { workspace = true }
ep-units = { workspace = true }
serde_json = { workspace = true }
